### ISSUE TITLE
The new version (v 0.18.1) cannot run in edge runtime.

### ISSUE THREAD

**Issue by mggger** [Unstructured-IO/unstructured-js-client#127]
Hi @awalker4 

I am using the latest version 0.18.1, but encountered an error and cannot run it under edge runtime.

```
 ⨯ Error [UnexpectedClientError]: Unexpected HTTP client error: Error: The edge runtime does not support Node.js 'crypto' module.
Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime
    at eval (webpack-internal:///(middleware)/./node_modules/unstructured-client/lib/sdks.js:186:45)
    at async generalPartition (webpack-internal:///(middleware)/./node_modules/unstructured-client/funcs/generalPartition.js:181:22)
    at async unwrapAsync (webpack-internal:///(middleware)/./node_modules/unstructured-client/sdk/types/fp.js:31:15)
    at async processWithUnstructured (webpack-internal:///(middleware)/./src/pages/api/upload/extract.js:67:17)
    at async Object.handler (webpack-internal:///(middleware)/./src/pages/api/upload/extract.js:234:30)
    at async adapter (webpack-internal:///(middleware)/./node_modules/next/dist/esm/server/web/adapter.js:176:16)
    at async runWithTaggedErrors (file:///Users/home/git/chatbots/abcb/node_modules/next/dist/server/web/sandbox/sandbox.js:99:24)
    at async DevServer.runEdgeFunction (file:///Users/home/git/chatbots/abcb/node_modules/next/dist/server/next-server.js:1166:24)
    at async NextNodeServer.handleCatchallRenderRequest (file:///Users/home/git/chatbots/abcb/node_modules/next/dist/server/next-server.js:245:37)
    at async DevServer.handleRequestImpl (file:///Users/home/git/chatbots/abcb/node_modules/next/dist/server/base-server.js:791:17)
```

**Comment by awalker4** [comment]
Ah, apologies about that! I'll get a fix going - in the meantime the workaround would be to use splitPdfPage: false.

**Comment by mggger** [comment]
@awalker4   Setting it to false still results in the same error.

**Comment by silvafabian** [comment]
@awalker4 Was there an update to this fix? I am running into the same issue using quasar-cli-webpack with vue3. I tried running it on localhost and get the same error as @mggger
